// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Runrs.DataAccess.Data;

#nullable disable

namespace Runrs.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Runrs.Models.Club", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClubDescription")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ClubLocation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ClubName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<int>("Distance")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("bit");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Clubs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClubDescription = "Join us every Wednesday & Saturday for a 10km run along Petone Esplanade/Beach",
                            ClubLocation = "Petone, Wellington",
                            ClubName = "Hutt Valley Run Club",
                            CreatedAt = new DateTime(2026, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Difficulty = 1,
                            Distance = 1,
                            ImageUrl = "https://wordpress.nzrunning.co.nz/wp-content/uploads/2025/04/445cover.jpg",
                            IsPrivate = false,
                            OwnerId = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            ClubDescription = "Wanting a challenge? Join our run club that regularly does the famous 'Bays Route', a 30km scenic route along some of the most beautiful bays Wellington has to offer.",
                            ClubLocation = "Wellington CBD, Wellington",
                            ClubName = "Bay Runners",
                            CreatedAt = new DateTime(2026, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Difficulty = 2,
                            Distance = 2,
                            ImageUrl = "https://www.changefitness.co.nz/wp-content/uploads/feb78d35-680f-4f15-81c1-1e7a0183f311.jpg",
                            IsPrivate = false,
                            OwnerId = 2,
                            Type = 3
                        },
                        new
                        {
                            Id = 3,
                            ClubDescription = "Join our social run club based in Porirua which is open to all levels of fitness. We meet every Saturday at the Porirua pools to complete a 5km run and socialise over coffee after. ",
                            ClubLocation = "Porirua, Wellington",
                            ClubName = "Social Runners WLG",
                            CreatedAt = new DateTime(2026, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Difficulty = 0,
                            Distance = 1,
                            ImageUrl = "https://cdn.eventfinda.co.nz/uploads/events/transformed/1771695-766708-34.jpg",
                            IsPrivate = false,
                            OwnerId = 3,
                            Type = 2
                        });
                });

            modelBuilder.Entity("Runrs.Models.EventRegistration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RunEventId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("UserId");

                    b.ToTable("EventRegistrations");
                });

            modelBuilder.Entity("Runrs.Models.Friendship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddresseeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RequesterId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AddresseeId");

                    b.HasIndex("RequesterId");

                    b.ToTable("Friendships");
                });

            modelBuilder.Entity("Runrs.Models.Membership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClubId")
                        .HasColumnType("int");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.HasIndex("UserId");

                    b.ToTable("Memberships");
                });

            modelBuilder.Entity("Runrs.Models.RunEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClubId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("Distance")
                        .HasColumnType("float");

                    b.Property<decimal?>("EntryFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("EventLocation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EventTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.ToTable("RunEvents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClubId = 1,
                            CreatedAt = new DateTime(2026, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Distance = 10.0,
                            EntryFee = 0m,
                            EventDate = new DateTime(2026, 11, 15, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            EventDescription = "Join us for a run along Petone Esplanade. This event will be an introductory event for any new members wanting to come and feel out the club!",
                            EventLocation = "Petone Esplanade, Wellington",
                            EventTitle = "Petone Run For Fun",
                            MaxParticipants = 20
                        },
                        new
                        {
                            Id = 2,
                            ClubId = 2,
                            CreatedAt = new DateTime(2026, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Distance = 30.0,
                            EntryFee = 20m,
                            EventDate = new DateTime(2026, 11, 22, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            EventDescription = "The annual BAYS ROUTE MARATHON is coming up. Join us to raise money for local charities in Wellington.",
                            EventLocation = "Wellington Waterfront, Wellington",
                            EventTitle = "Bays Route Marathon",
                            MaxParticipants = 50
                        },
                        new
                        {
                            Id = 3,
                            ClubId = 3,
                            CreatedAt = new DateTime(2026, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Distance = 5.0,
                            EntryFee = 0m,
                            EventDate = new DateTime(2026, 6, 6, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            EventDescription = "Our weekly Saturday 5km social run followed by coffee.",
                            EventLocation = "Porirua Pools, Porirua",
                            EventTitle = "Porirua 5km Social Run",
                            MaxParticipants = 50
                        });
                });

            modelBuilder.Entity("Runrs.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(1999, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Test@gmail.com",
                            FirstName = "Test",
                            JoinedAt = new DateTime(2026, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "User",
                            PasswordHash = "Test123",
                            Username = "testuser"
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(1999, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Test2@gmail.com",
                            FirstName = "Test2",
                            JoinedAt = new DateTime(2026, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "User2",
                            PasswordHash = "Test123",
                            Username = "testuser2"
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(1999, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Test@gmail.com",
                            FirstName = "Test3",
                            JoinedAt = new DateTime(2026, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "User3",
                            PasswordHash = "Test123",
                            Username = "testuser3"
                        });
                });

            modelBuilder.Entity("Runrs.Models.Club", b =>
                {
                    b.HasOne("Runrs.Models.User", "Owner")
                        .WithMany("OwnedClubs")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Runrs.Models.EventRegistration", b =>
                {
                    b.HasOne("Runrs.Models.RunEvent", "RunEvent")
                        .WithMany("Registrations")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Runrs.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("RunEvent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Runrs.Models.Friendship", b =>
                {
                    b.HasOne("Runrs.Models.User", "Addressee")
                        .WithMany()
                        .HasForeignKey("AddresseeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Runrs.Models.User", "Requester")
                        .WithMany()
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Addressee");

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("Runrs.Models.Membership", b =>
                {
                    b.HasOne("Runrs.Models.Club", "Club")
                        .WithMany("Memberships")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Runrs.Models.User", "User")
                        .WithMany("Memberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Runrs.Models.RunEvent", b =>
                {
                    b.HasOne("Runrs.Models.Club", "Club")
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");
                });

            modelBuilder.Entity("Runrs.Models.Club", b =>
                {
                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("Runrs.Models.RunEvent", b =>
                {
                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("Runrs.Models.User", b =>
                {
                    b.Navigation("Memberships");

                    b.Navigation("OwnedClubs");
                });
#pragma warning restore 612, 618
        }
    }
}
