// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Runrs_SD7501.Data;

#nullable disable

namespace Runrs_SD7501.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260417092757_AddNewSeedDataUserAndClub")]
    partial class AddNewSeedDataUserAndClub
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Runrs_SD7501.Models.Club", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClubDescription")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ClubLocation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ClubName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("bit");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Clubs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClubDescription = "Join us every Wednesday & Saturday for a 10km run along Petone Esplanade/Beach",
                            ClubLocation = "Petone, Wellington",
                            ClubName = "Hutt Valley Run Club",
                            CreatedAt = new DateTime(2026, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "",
                            IsPrivate = false,
                            OwnerId = 1
                        },
                        new
                        {
                            Id = 2,
                            ClubDescription = "Wanting a challenge? Join our run club that regularly does the famous 'Bays Route', a 30km scenic route along some of the most beautiful bays Wellington has to offer.",
                            ClubLocation = "Wellington CBD, Wellington",
                            ClubName = "Bay Runners",
                            CreatedAt = new DateTime(2026, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "",
                            IsPrivate = false,
                            OwnerId = 2
                        },
                        new
                        {
                            Id = 3,
                            ClubDescription = "Join our social run club based in Porirua which is open to all levels of fitness. We meet every Saturday at the Porirua pools to complete a 5km run and socialise over coffee after. ",
                            ClubLocation = "Porirua, Wellington",
                            ClubName = "Social Runners WLG",
                            CreatedAt = new DateTime(2026, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "",
                            IsPrivate = false,
                            OwnerId = 3
                        });
                });

            modelBuilder.Entity("Runrs_SD7501.Models.Membership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClubId")
                        .HasColumnType("int");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.HasIndex("UserId");

                    b.ToTable("Memberships");
                });

            modelBuilder.Entity("Runrs_SD7501.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(1999, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Test@gmail.com",
                            FirstName = "Test",
                            JoinedAt = new DateTime(2026, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "User",
                            PasswordHash = "Test123",
                            Username = "testuser"
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(1999, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Test2@gmail.com",
                            FirstName = "Test2",
                            JoinedAt = new DateTime(2026, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "User2",
                            PasswordHash = "Test123",
                            Username = "testuser2"
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(1999, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Test@gmail.com",
                            FirstName = "Test3",
                            JoinedAt = new DateTime(2026, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "User3",
                            PasswordHash = "Test123",
                            Username = "testuser3"
                        });
                });

            modelBuilder.Entity("Runrs_SD7501.Models.Club", b =>
                {
                    b.HasOne("Runrs_SD7501.Models.User", "Owner")
                        .WithMany("OwnedClubs")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Runrs_SD7501.Models.Membership", b =>
                {
                    b.HasOne("Runrs_SD7501.Models.Club", "Club")
                        .WithMany("Memberships")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Runrs_SD7501.Models.User", "User")
                        .WithMany("Memberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Runrs_SD7501.Models.Club", b =>
                {
                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("Runrs_SD7501.Models.User", b =>
                {
                    b.Navigation("Memberships");

                    b.Navigation("OwnedClubs");
                });
#pragma warning restore 612, 618
        }
    }
}
